#!/bin/bash
##################################################################
##								##
##								##
##Dependencies	:						##
##Influences	:						##
##################################################################
## ver.	: 2019--, Syamal Praneeth Chilakalapudi, KIT, INT	##
##Author Email    :syamalpraneeth@gmail.com			##
##################################################################

acro='acronyms.csv'
glos='glossary.csv'

glostex='sections/glossary.tex'

echo -e % Autogenerated acronyms from $acro > $glostex "\n \n"

#Glossary Items
while IFS=, read -r col1 col2 col3
do
    echo "\n"ewglossaryentry{$col1}{>> $glostex;
    echo "\n"ewglossaryentry{$col1}{;
    echo -e name={$col2}\,"\n"description={$col3}"\n"}"\n">> $glostex;
    echo -e name={$col2}\,"\n"description={$col3}"\n"}"\n";
done < $glos

#Acronym Items
while IFS=, read -r col1 col2 col3
do
    echo "\n"ewacronym{$col1}{$col2}{$col3} >> $glostex;
    echo "\n"ewacronym{$col1}{$col2}{$col3};
done < $acro
